spring:
  application:
    name: book-service
server:
  port: 2001
eureka:
  client:
    serviceUrl:
      defaultZone:  http://127.0.0.1:1001/eureka/

  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapperLocations: classpath*:mybatis/mapper-*.xml
  typeAliasesPackage: org.zys.user.model

mongdb:
  mongo.host: localhost
  mongo.port: 27017
  mongo.dbname: 1810B
redis:
    #redis数据库索引(默认为0)
    database : 0
    #redis服务器地址
    host: localhost
    #redis服务器连接端口
    port: 6379
    #redis连接密码
    password:
    #redis连接池设置
    pool:
      #最大空闲连接
      max-idle : 100
      #最小空闲连接
      min-idle : 1
      #最大连接数(负数表示没有限制)
      max-active : 1000
      #最大阻塞等待时间(负数表示没有限制)
      max-wait : -1
      #连接超时时间(毫秒)
      timeout : 0
